[package]
name = "site-generation"
version = "0.1.0"
edition = "2021"

[dependencies]
comrak = "0.13.0"
dsl = { path = "dsl" }
serde = { version = "1.0.81", features = ["derive"] }
serde_json = "1.0.81"

